<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE DSExport [
   <!ELEMENT DSExport (Header, (Job |
                                SharedContainer |
                                IMSDatabase |
                                IMSViewset |
                                DataElements |
                                MachineProfiles |
                                Routines |
                                StageTypes |
                                TableDefinitions |
                                Transforms)+
                      ) >
   <!ELEMENT Header EMPTY >
      <!ATTLIST Header
                           CharacterSet   CDATA   #IMPLIED
                           ExportingTool  CDATA   #IMPLIED
                           ToolVersion    CDATA   #REQUIRED
                           ServerName     CDATA   #IMPLIED
                           ToolInstanceID CDATA   #IMPLIED
                           Date           CDATA   #IMPLIED
                           Time           CDATA   #IMPLIED
                           ServerVersion  CDATA   #IMPLIED
      >
   <!ELEMENT Job (Record*) >
      <!ATTLIST Job
                           Identifier     CDATA   #REQUIRED
                           DateModified   CDATA   #IMPLIED
                           TimeModified   CDATA   #IMPLIED
     >
   <!ELEMENT SharedContainer (Record*) >
      <!ATTLIST SharedContainer
                           Identifier     CDATA   #REQUIRED
                           DateModified   CDATA   #IMPLIED
                           TimeModified   CDATA   #IMPLIED
     >
   <!ELEMENT IMSDatabase (Record*) >
      <!ATTLIST IMSDatabase
                           Identifier     CDATA   #REQUIRED
                           DateModified   CDATA   #IMPLIED
                           TimeModified   CDATA   #IMPLIED
     >
   <!ELEMENT IMSViewset (Record*) >
      <!ATTLIST IMSViewset
                           Identifier     CDATA   #REQUIRED
                           DateModified   CDATA   #IMPLIED
                           TimeModified   CDATA   #IMPLIED
     >
   <!ELEMENT DataElements (Record*) >
   <!ELEMENT MachineProfiles (Record*) >
   <!ELEMENT Routines (Record*) >
   <!ELEMENT StageTypes (Record*) >
   <!ELEMENT TableDefinitions (Record*) >
   <!ELEMENT Transforms (Record*) >
   <!ELEMENT Record ((Property | Collection)*) >
     <!ATTLIST Record
                           Identifier     CDATA   #REQUIRED
                           DateModified   CDATA   #IMPLIED
                           TimeModified   CDATA   #IMPLIED
                           Type           CDATA   #REQUIRED
                           Readonly       (0|1)   '0'
                           IsStage        (0|1)   '0'
      >
   <!ELEMENT Property (#PCDATA | ListItem | DSXML)*  >
      <!ATTLIST Property
                           Name           CDATA   #REQUIRED
                           PreFormatted   (0|1)   '0'
                           xml:space      (default|preserve) 'preserve'
      >
   <!ELEMENT ListItem (#PCDATA)* >
      <!ATTLIST ListItem
                           DisplayName    CDATA   #REQUIRED
                           xml:space      (default|preserve) 'preserve'
      >
   <!ELEMENT DSXML ANY >
   <!ELEMENT Collection (Record*) >
      <!ATTLIST Collection
                           Name           CDATA   #REQUIRED
                           Type           CDATA   #REQUIRED
      >
<!--   <!ELEMENT Record (Property*) > -->
]>
<DSExport>
   <Header CharacterSet="ENGLISH" ExportingTool="Ascential DataStage Export (External)" ToolVersion="4" ServerName="srvDStageProd" ToolInstanceID="DiffusionReglement" Date="2011-03-31" Time="18.19.14" ServerVersion="7.5.1.A" ClientInstallPath="C:\Program Files\Ascential\DataStage7.5.1"/>
   <Job Identifier="Protide_Effiport" DateModified="2007-07-13" TimeModified="10.47.34">
      <Record Identifier="ROOT" DateModified="1899-12-30" TimeModified="00.00.01" Type="JobDefn" Readonly="0">
         <Property Name="Name">Protide_Effiport</Property>
         <Property Name="NextID">1</Property>
         <Property Name="Container">V0</Property>
         <Property Name="JobVersion">50.0.0</Property>
         <Property Name="ControlAfterSubr">0</Property>
         <Collection Name="Parameters" Type="Parameters">
            <Record Type="Subr">
               <Property Name="Name">Base</Property>
               <Property Name="Prompt">Nom de la base destination</Property>
               <Property Name="Default">DiffusionReglementaire</Property>
               <Property Name="ParamType">String</Property>
            </Record>
            <Record Type="Subr">
               <Property Name="Name">Login</Property>
               <Property Name="Prompt">LoginSQL</Property>
               <Property Name="Default">DiffusionReglementaire</Property>
               <Property Name="ParamType">String</Property>
               <Property Name="ParamLength">0</Property>
               <Property Name="ParamScale">0</Property>
            </Record>
            <Record Type="Subr">
               <Property Name="Name">Password</Property>
               <Property Name="Prompt">PasswordSQL</Property>
               <Property Name="Default">LD;D9;VHM9K&gt;0?DI4HJ&lt;CKID</Property>
               <Property Name="ParamType">Encrypted</Property>
               <Property Name="ParamLength">0</Property>
               <Property Name="ParamScale">0</Property>
            </Record>
            <Record Type="Subr">
               <Property Name="Name">Chemin</Property>
               <Property Name="Prompt">Chemin Protide</Property>
               <Property Name="Default">d:\Transfert\DiffusionReglementaire\Protide</Property>
               <Property Name="ParamType">String</Property>
               <Property Name="ParamLength">0</Property>
               <Property Name="ParamScale">0</Property>
            </Record>
            <Record Type="Subr">
               <Property Name="Name">RepertoireSource</Property>
               <Property Name="Prompt">R&#xE9;pertoire fichier source</Property>
               <Property Name="Default">O:\Effiport\Ecr\</Property>
               <Property Name="ParamType">String</Property>
               <Property Name="ParamLength">0</Property>
               <Property Name="ParamScale">0</Property>
            </Record>
            <Record Type="Subr">
               <Property Name="Name">FichierSource</Property>
               <Property Name="Prompt">FichierSource</Property>
               <Property Name="Default">PROTIDE.SPV</Property>
               <Property Name="ParamType">String</Property>
               <Property Name="ParamLength">0</Property>
               <Property Name="ParamScale">0</Property>
            </Record>
         </Collection>
         <Collection Name="MetaBag" Type="MetaProperty">
            <Record Type="Subr">
               <Property Name="Owner">APT</Property>
               <Property Name="Name">AdvancedRuntimeOptions</Property>
               <Property Name="Value">#DSProjectARTOptions#</Property>
            </Record>
         </Collection>
         <Property Name="IsTemplate">0</Property>
         <Property Name="NLSLocale" PreFormatted="1">Time=(Project default)
Numeric=(Project default)
Currency=(Project default)
CType=(Project default)
Collate=(Project default)</Property>
         <Property Name="JobType">Server</Property>
         <Property Name="Category">TCC</Property>
         <Property Name="CenturyBreakYear">30</Property>
         <Property Name="NextAliasID">2</Property>
         <Property Name="ParameterFileDDName">DD00001</Property>
         <Property Name="ReservedWordCheck">Yes</Property>
         <Property Name="ValidationStatus">0</Property>
         <Property Name="Uploadable">0</Property>
         <Property Name="PgmCustomizationFlag">0</Property>
         <Property Name="JobReportFlag">0</Property>
         <Property Name="AllowMultipleInvocations">0</Property>
         <Property Name="Act2ActOverideDefaults">0</Property>
         <Property Name="Act2ActEnableRowBuffer">0</Property>
         <Property Name="Act2ActUseIPC">0</Property>
         <Property Name="EnableCacheSharing">0</Property>
         <Property Name="RuntimeColumnPropagation">0</Property>
         <Property Name="RelStagesInJobStatus">-1</Property>
         <Property Name="WebServiceEnabled">0</Property>
         <Property Name="CopyLibPrefix">ARDT</Property>
      </Record>
      <Record Identifier="V0" DateModified="1899-12-30" TimeModified="00.00.01" Type="ContainerView" Readonly="0">
         <Property Name="Name">Job</Property>
         <Property Name="NextID">1</Property>
         <Property Name="IsTopLevel">0</Property>
         <Property Name="StageList">V0S0|V0S1|V0S2</Property>
         <Property Name="StageXPos">72|408|240</Property>
         <Property Name="StageYPos">72|72|72</Property>
         <Property Name="StageTypes">CSeqFileStage|CODBCStage|CTransformerStage</Property>
         <Property Name="NextStageID">5</Property>
         <Property Name="SnapToGrid">1</Property>
         <Property Name="GridLines">0</Property>
         <Property Name="ZoomValue">100</Property>
         <Property Name="StageXSize">48|48|48</Property>
         <Property Name="StageYSize">48|48|48</Property>
         <Property Name="ContainerViewSizing">0000 0000 0745 0543 0000 0000 0000 0000</Property>
      </Record>
      <Record Identifier="V0S0" DateModified="1899-12-30" TimeModified="00.00.01" Type="SeqFileStage" Readonly="0" IsStage="1">
         <Property Name="Name">Effiport</Property>
         <Property Name="NextID">2</Property>
         <Property Name="OutputPins">V0S0P1</Property>
         <Property Name="UnixFormat">DOS</Property>
         <Property Name="PipeStage">File</Property>
         <Property Name="UnicodeBOM">1</Property>
         <Property Name="UnicodeSwapped">1</Property>
         <Property Name="WithFilter">0</Property>
         <Property Name="StageType">CSeqFileStage</Property>
      </Record>
      <Record Identifier="V0S0P1" DateModified="1899-12-30" TimeModified="00.00.01" Type="SeqOutput" Readonly="0">
         <Property Name="Name">DSLink3</Property>
         <Property Name="Partner">V0S2</Property>
         <Property Name="FileName">#Chemin#\#FichierSource#</Property>
         <Property Name="ColDelim">,</Property>
         <Property Name="QuoteChar">&quot;</Property>
         <Property Name="ColHeaders">0</Property>
         <Property Name="FixedWidth">1</Property>
         <Property Name="ColSpace">0</Property>
         <Property Name="EnforceMetaData">Pad with SQL NULL</Property>
         <Property Name="Readtimeout">0</Property>
         <Collection Name="Columns" Type="OutputColumn">
            <Record Type="Subr">
               <Property Name="Name">ISIN</Property>
               <Property Name="SqlType">Char</Property>
               <Property Name="Precision">12</Property>
               <Property Name="DisplaySize">12</Property>
               <Property Name="AllowCRLF">No</Property>
               <Property Name="PadChar"/>
               <Property Name="ExtendedType">Char(12)</Property>
            </Record>
            <Record Type="Subr">
               <Property Name="Name">Libelle_valeur</Property>
               <Property Name="Description" PreFormatted="1">&lt;none&gt;
Searchable? N </Property>
               <Property Name="SqlType">VarChar</Property>
               <Property Name="Precision">30</Property>
               <Property Name="Nullable">No</Property>
               <Property Name="KeyPosition">No</Property>
               <Property Name="DisplaySize">30</Property>
               <Property Name="Group">No</Property>
               <Property Name="TableDef">ODBC\DiffusionReglementaire\DiffusionReglementaire.dbo.Protide_Effiport</Property>
               <Property Name="AllowCRLF">No</Property>
               <Property Name="PadNulls">Error</Property>
               <Property Name="SortingOrder">Ascending</Property>
               <Property Name="ArrayHandling">0</Property>
               <Property Name="PadChar"/>
               <Property Name="ColumnReference">Libelle_valeur</Property>
               <Property Name="TaggedSubrec">0</Property>
               <Property Name="OccursVarying">0</Property>
               <Property Name="PKeyIsCaseless">0</Property>
               <Property Name="ExtendedType">VarChar(30)</Property>
            </Record>
            <Record Type="Subr">
               <Property Name="Name">Type_portefeuille</Property>
               <Property Name="Description" PreFormatted="1">&lt;none&gt;
Searchable? N </Property>
               <Property Name="SqlType">Char</Property>
               <Property Name="Precision">3</Property>
               <Property Name="Nullable">No</Property>
               <Property Name="KeyPosition">No</Property>
               <Property Name="DisplaySize">3</Property>
               <Property Name="Group">No</Property>
               <Property Name="TableDef">ODBC\DiffusionReglementaire\DiffusionReglementaire.dbo.Protide_Effiport</Property>
               <Property Name="AllowCRLF">No</Property>
               <Property Name="PadNulls">Error</Property>
               <Property Name="SortingOrder">Ascending</Property>
               <Property Name="ArrayHandling">0</Property>
               <Property Name="PadChar"/>
               <Property Name="ColumnReference">Type_portefeuille</Property>
               <Property Name="TaggedSubrec">0</Property>
               <Property Name="OccursVarying">0</Property>
               <Property Name="PKeyIsCaseless">0</Property>
               <Property Name="ExtendedType">Char(3)</Property>
            </Record>
            <Record Type="Subr">
               <Property Name="Name">Type_detention</Property>
               <Property Name="Description" PreFormatted="1">&lt;none&gt;
Searchable? N </Property>
               <Property Name="SqlType">Char</Property>
               <Property Name="Precision">3</Property>
               <Property Name="Nullable">No</Property>
               <Property Name="KeyPosition">No</Property>
               <Property Name="DisplaySize">3</Property>
               <Property Name="Group">No</Property>
               <Property Name="TableDef">ODBC\DiffusionReglementaire\DiffusionReglementaire.dbo.Protide_Effiport</Property>
               <Property Name="AllowCRLF">No</Property>
               <Property Name="PadNulls">Error</Property>
               <Property Name="SortingOrder">Ascending</Property>
               <Property Name="ArrayHandling">0</Property>
               <Property Name="PadChar"/>
               <Property Name="ColumnReference">Type_detention</Property>
               <Property Name="TaggedSubrec">0</Property>
               <Property Name="OccursVarying">0</Property>
               <Property Name="PKeyIsCaseless">0</Property>
               <Property Name="ExtendedType">Char(3)</Property>
            </Record>
            <Record Type="Subr">
               <Property Name="Name">Secteur_detenteur</Property>
               <Property Name="Description" PreFormatted="1">&lt;none&gt;
Searchable? N </Property>
               <Property Name="SqlType">Char</Property>
               <Property Name="Precision">4</Property>
               <Property Name="Nullable">No</Property>
               <Property Name="KeyPosition">No</Property>
               <Property Name="DisplaySize">4</Property>
               <Property Name="Group">No</Property>
               <Property Name="TableDef">ODBC\DiffusionReglementaire\DiffusionReglementaire.dbo.Protide_Effiport</Property>
               <Property Name="AllowCRLF">No</Property>
               <Property Name="PadNulls">Error</Property>
               <Property Name="SortingOrder">Ascending</Property>
               <Property Name="ArrayHandling">0</Property>
               <Property Name="PadChar"/>
               <Property Name="ColumnReference">Secteur_detenteur</Property>
               <Property Name="APTFieldProp">quote=none</Property>
               <Property Name="TaggedSubrec">0</Property>
               <Property Name="OccursVarying">0</Property>
               <Property Name="PKeyIsCaseless">0</Property>
               <Property Name="ExtendedType">Char(4)</Property>
            </Record>
            <Record Type="Subr">
               <Property Name="Name">Zone_geo_detenteur</Property>
               <Property Name="Description" PreFormatted="1">&lt;none&gt;
Searchable? N </Property>
               <Property Name="SqlType">Char</Property>
               <Property Name="Precision">2</Property>
               <Property Name="Nullable">No</Property>
               <Property Name="KeyPosition">No</Property>
               <Property Name="DisplaySize">2</Property>
               <Property Name="Group">No</Property>
               <Property Name="TableDef">ODBC\DiffusionReglementaire\DiffusionReglementaire.dbo.Protide_Effiport</Property>
               <Property Name="AllowCRLF">No</Property>
               <Property Name="PadNulls">Error</Property>
               <Property Name="SortingOrder">Ascending</Property>
               <Property Name="ArrayHandling">0</Property>
               <Property Name="PadChar"/>
               <Property Name="ColumnReference">Zone_geo_detenteur</Property>
               <Property Name="TaggedSubrec">0</Property>
               <Property Name="OccursVarying">0</Property>
               <Property Name="PKeyIsCaseless">0</Property>
               <Property Name="ExtendedType">Char(2)</Property>
            </Record>
            <Record Type="Subr">
               <Property Name="Name">Pays_detenteur</Property>
               <Property Name="Description" PreFormatted="1">&lt;none&gt;
Searchable? N </Property>
               <Property Name="SqlType">Char</Property>
               <Property Name="Precision">2</Property>
               <Property Name="Nullable">No</Property>
               <Property Name="KeyPosition">No</Property>
               <Property Name="DisplaySize">2</Property>
               <Property Name="Group">No</Property>
               <Property Name="TableDef">ODBC\DiffusionReglementaire\DiffusionReglementaire.dbo.Protide_Effiport</Property>
               <Property Name="AllowCRLF">No</Property>
               <Property Name="PadNulls">Error</Property>
               <Property Name="SortingOrder">Ascending</Property>
               <Property Name="ArrayHandling">0</Property>
               <Property Name="PadChar"/>
               <Property Name="ColumnReference">Pays_detenteur</Property>
               <Property Name="TaggedSubrec">0</Property>
               <Property Name="OccursVarying">0</Property>
               <Property Name="PKeyIsCaseless">0</Property>
               <Property Name="ExtendedType">Char(2)</Property>
            </Record>
            <Record Type="Subr">
               <Property Name="Name">Nature_intsrument</Property>
               <Property Name="Description" PreFormatted="1">&lt;none&gt;
Searchable? N </Property>
               <Property Name="SqlType">Char</Property>
               <Property Name="Precision">3</Property>
               <Property Name="Nullable">No</Property>
               <Property Name="KeyPosition">No</Property>
               <Property Name="DisplaySize">3</Property>
               <Property Name="Group">No</Property>
               <Property Name="TableDef">ODBC\DiffusionReglementaire\DiffusionReglementaire.dbo.Protide_Effiport</Property>
               <Property Name="AllowCRLF">No</Property>
               <Property Name="PadNulls">Error</Property>
               <Property Name="SortingOrder">Ascending</Property>
               <Property Name="ArrayHandling">0</Property>
               <Property Name="PadChar"/>
               <Property Name="ColumnReference">Nature_intsrument</Property>
               <Property Name="TaggedSubrec">0</Property>
               <Property Name="OccursVarying">0</Property>
               <Property Name="PKeyIsCaseless">0</Property>
               <Property Name="ExtendedType">Char(3)</Property>
            </Record>
            <Record Type="Subr">
               <Property Name="Name">Monnaie_titre</Property>
               <Property Name="Description" PreFormatted="1">&lt;none&gt;
Searchable? N </Property>
               <Property Name="SqlType">Char</Property>
               <Property Name="Precision">3</Property>
               <Property Name="Nullable">No</Property>
               <Property Name="KeyPosition">No</Property>
               <Property Name="DisplaySize">3</Property>
               <Property Name="Group">No</Property>
               <Property Name="TableDef">ODBC\DiffusionReglementaire\DiffusionReglementaire.dbo.Protide_Effiport</Property>
               <Property Name="AllowCRLF">No</Property>
               <Property Name="PadNulls">Error</Property>
               <Property Name="SortingOrder">Ascending</Property>
               <Property Name="ArrayHandling">0</Property>
               <Property Name="PadChar"/>
               <Property Name="ColumnReference">Monnaie_titre</Property>
               <Property Name="TaggedSubrec">0</Property>
               <Property Name="OccursVarying">0</Property>
               <Property Name="PKeyIsCaseless">0</Property>
               <Property Name="ExtendedType">Char(3)</Property>
            </Record>
            <Record Type="Subr">
               <Property Name="Name">Zone_geo_emetteur</Property>
               <Property Name="Description" PreFormatted="1">&lt;none&gt;
Searchable? N </Property>
               <Property Name="SqlType">Char</Property>
               <Property Name="Precision">2</Property>
               <Property Name="Nullable">No</Property>
               <Property Name="KeyPosition">No</Property>
               <Property Name="DisplaySize">2</Property>
               <Property Name="Group">No</Property>
               <Property Name="TableDef">ODBC\DiffusionReglementaire\DiffusionReglementaire.dbo.Protide_Effiport</Property>
               <Property Name="AllowCRLF">No</Property>
               <Property Name="PadNulls">Error</Property>
               <Property Name="SortingOrder">Ascending</Property>
               <Property Name="ArrayHandling">0</Property>
               <Property Name="PadChar"/>
               <Property Name="ColumnReference">Zone_geo_emetteur</Property>
               <Property Name="TaggedSubrec">0</Property>
               <Property Name="OccursVarying">0</Property>
               <Property Name="PKeyIsCaseless">0</Property>
               <Property Name="ExtendedType">Char(2)</Property>
            </Record>
            <Record Type="Subr">
               <Property Name="Name">Secteur_emetteur</Property>
               <Property Name="Description" PreFormatted="1">&lt;none&gt;
Searchable? N </Property>
               <Property Name="SqlType">Char</Property>
               <Property Name="Precision">4</Property>
               <Property Name="Nullable">No</Property>
               <Property Name="KeyPosition">No</Property>
               <Property Name="DisplaySize">4</Property>
               <Property Name="Group">No</Property>
               <Property Name="TableDef">ODBC\DiffusionReglementaire\DiffusionReglementaire.dbo.Protide_Effiport</Property>
               <Property Name="AllowCRLF">No</Property>
               <Property Name="PadNulls">Error</Property>
               <Property Name="SortingOrder">Ascending</Property>
               <Property Name="ArrayHandling">0</Property>
               <Property Name="PadChar"/>
               <Property Name="ColumnReference">Secteur_emetteur</Property>
               <Property Name="APTFieldProp">quote=none</Property>
               <Property Name="TaggedSubrec">0</Property>
               <Property Name="OccursVarying">0</Property>
               <Property Name="PKeyIsCaseless">0</Property>
               <Property Name="ExtendedType">Char(4)</Property>
            </Record>
            <Record Type="Subr">
               <Property Name="Name">Pays_emetteur</Property>
               <Property Name="Description" PreFormatted="1">&lt;none&gt;
Searchable? N </Property>
               <Property Name="SqlType">Char</Property>
               <Property Name="Precision">2</Property>
               <Property Name="Nullable">No</Property>
               <Property Name="KeyPosition">No</Property>
               <Property Name="DisplaySize">2</Property>
               <Property Name="Group">No</Property>
               <Property Name="TableDef">ODBC\DiffusionReglementaire\DiffusionReglementaire.dbo.Protide_Effiport</Property>
               <Property Name="AllowCRLF">No</Property>
               <Property Name="PadNulls">Error</Property>
               <Property Name="SortingOrder">Ascending</Property>
               <Property Name="ArrayHandling">0</Property>
               <Property Name="PadChar"/>
               <Property Name="ColumnReference">Pays_emetteur</Property>
               <Property Name="TaggedSubrec">0</Property>
               <Property Name="OccursVarying">0</Property>
               <Property Name="PKeyIsCaseless">0</Property>
               <Property Name="ExtendedType">Char(2)</Property>
            </Record>
            <Record Type="Subr">
               <Property Name="Name">Encours_periode_precedente</Property>
               <Property Name="Description" PreFormatted="1">&lt;none&gt;
Searchable? N </Property>
               <Property Name="SqlType">Numeric</Property>
               <Property Name="Precision">18</Property>
               <Property Name="Scale">2</Property>
               <Property Name="Nullable">Yes</Property>
               <Property Name="KeyPosition">No</Property>
               <Property Name="DisplaySize">18</Property>
               <Property Name="Group">No</Property>
               <Property Name="TableDef">ODBC\DiffusionReglementaire\DiffusionReglementaire.dbo.Protide_Effiport</Property>
               <Property Name="AllowCRLF">No</Property>
               <Property Name="PadNulls">Error</Property>
               <Property Name="SortingOrder">Ascending</Property>
               <Property Name="ArrayHandling">0</Property>
               <Property Name="PadChar"/>
               <Property Name="ColumnReference">Encours_periode_precedente</Property>
               <Property Name="APTFieldProp">quote=none, null_field=&apos;&apos;</Property>
               <Property Name="TaggedSubrec">0</Property>
               <Property Name="OccursVarying">0</Property>
               <Property Name="PKeyIsCaseless">0</Property>
               <Property Name="ExtendedType">Numeric(18,2) nullable</Property>
            </Record>
            <Record Type="Subr">
               <Property Name="Name">Encours_periode</Property>
               <Property Name="Description" PreFormatted="1">&lt;none&gt;
Searchable? N </Property>
               <Property Name="SqlType">Numeric</Property>
               <Property Name="Precision">18</Property>
               <Property Name="Scale">2</Property>
               <Property Name="Nullable">No</Property>
               <Property Name="KeyPosition">No</Property>
               <Property Name="DisplaySize">18</Property>
               <Property Name="Group">No</Property>
               <Property Name="TableDef">ODBC\DiffusionReglementaire\DiffusionReglementaire.dbo.Protide_Effiport</Property>
               <Property Name="AllowCRLF">No</Property>
               <Property Name="PadNulls">Error</Property>
               <Property Name="SortingOrder">Ascending</Property>
               <Property Name="ArrayHandling">0</Property>
               <Property Name="PadChar"/>
               <Property Name="ColumnReference">Encours_periode</Property>
               <Property Name="APTFieldProp">quote=none</Property>
               <Property Name="TaggedSubrec">0</Property>
               <Property Name="OccursVarying">0</Property>
               <Property Name="PKeyIsCaseless">0</Property>
               <Property Name="ExtendedType">Numeric(18,2)</Property>
            </Record>
            <Record Type="Subr">
               <Property Name="Name">Compte_titre</Property>
               <Property Name="Description" PreFormatted="1">&lt;none&gt;
Searchable? N </Property>
               <Property Name="SqlType">VarChar</Property>
               <Property Name="Precision">21</Property>
               <Property Name="Nullable">No</Property>
               <Property Name="KeyPosition">No</Property>
               <Property Name="DisplaySize">21</Property>
               <Property Name="Group">No</Property>
               <Property Name="TableDef">ODBC\DiffusionReglementaire\DiffusionReglementaire.dbo.Protide_Effiport</Property>
               <Property Name="AllowCRLF">No</Property>
               <Property Name="PadNulls">Error</Property>
               <Property Name="SortingOrder">Ascending</Property>
               <Property Name="ArrayHandling">0</Property>
               <Property Name="PadChar"/>
               <Property Name="ColumnReference">Compte_titre</Property>
               <Property Name="TaggedSubrec">0</Property>
               <Property Name="OccursVarying">0</Property>
               <Property Name="PKeyIsCaseless">0</Property>
               <Property Name="ExtendedType">VarChar(21)</Property>
            </Record>